DAPP_REPORT_JUDGE_TEMPLATE_SP = """
### Role Definition
You are a Chief Audit Expert in the field of blockchain security. Your task is to evaluate a "fault localization list" generated by an automated Agent (intern).
You have two inputs:
1. **Candidate Report (Intern Report)**: The localization list to be evaluated.
2. **Expert Report (Expert Standard/Ground Truth)**: The core conclusions provided by experts, serving as the benchmark for evaluation (Article/Source).

### Core Evaluation Principles
1. **Core Inclusion Principle**: Evaluate whether the list of faulty functions `ranked_suspicious_functions` provided by the intern contains the core conclusions from the expert report (such as vulnerable functions, vulnerability types). Fill in the `hit_rank` field with the rank of the true root cause function within the suspicious list, [1, 5]. If the rank is less than 1 or greater than 5, set it directly to -1. Any scenarios that cannot be handled should default to -1.

### Output Format
Please output in pure JSON format:
{
    "reasoning_trace": "Review reasoning chain: 1. Core conclusion hit determination; 2. Detailed scoring reasons regarding the 5 dimensions.",
    "hit_rank": 1,      # Rank in the suspicious list
    "feedback": "One-sentence comment pointing out specific pros and cons."
}
"""

DAPP_REPORT_JUDGE_TEMPLATE_UP = """
Please evaluate the fault localization report generated by the intern based on the benchmark conclusions provided by the expert.

<expert_ground_truth>
{answer}
</expert_ground_truth>

<candidate_report>
{problem}
</candidate_report>

Please output the result in JSON format.
"""